- reference : 
    - [Youtube : Julia Tutorial 2022 Korea 줄리아 언어 소개](https://www.youtube.com/watch?v=wjLXmz4D9VQ&t=2131s)
    - [Julia Tutorial 2022 Korea 줄리아 언어 소개 - 마크다운 문서](https://github.com/chkwon/JuliaTutorial2022Korea)

# 기본 연산 & 자료형
    - `String` 
    - `Char` 
    - `Int` 
    - `Float64`
    - `Bool` 
    - `Vector`
    - `Matrix`

In [21]:
1+1

2

## 문자열

- 문자열은 `""`를 사용한다. String
- `''`는 `Character`라는 별도의 자료형으로 표현된다.
- 포매팅 사용가능

In [2]:
println('hello world')

LoadError: syntax: character literal contains multiple characters

In [3]:
println("hello world")

hello world


In [12]:
a = "abc"
typeof(a)

String

In [18]:
b = 'a'
b

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [19]:
typeof(b)

Char

In [15]:
c = 'abc'

LoadError: syntax: character literal contains multiple characters

In [7]:
## 포매팅
abc = "Hello"
println("$abc World")
println("($abc)World")

Hello World
(Hello)World


## 숫자 자료형
- `Int` 
- `Float64`

In [9]:
Int

Int64

In [16]:
b = Int32(2)
typeof(b)

Int32

### 자료형의 Hiarachy


In [23]:
Int32 <: Integer

true

In [24]:
Int64 <: Integer

true

In [25]:
Char <: Integer

false

In [26]:
Bool <: Integer

true

In [27]:
Float32 <: AbstractFloat 

true

In [28]:
Float64 <: AbstractFloat 

true

In [29]:
Int64 <: Integer <: Real

true

In [31]:
String <: Integer <: Real

false

In [32]:
Float64 <: Real

true

In [34]:
z = 1.0 + 2.0* im # 복소수도 지원

1.0 + 2.0im

In [35]:
typeof(z)

ComplexF64 (alias for Complex{Float64})

In [37]:
Complex <: Number

true

In [38]:
Real <: Number

true

### 벡터, 매트릭스
    - 파이썬의 리스트와 같은 개념
    - 하지만 줄리아에선 어레이 개념으로 정의한다.
    - 인덱싱
        - 1부터 시작한다!
        - 파이썬 리스트의 인덱싱 방법도 다르다. (줄리아가 보다 직관적)

In [39]:
v = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [40]:
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

In [41]:
A = [ 1 2 3 4;
    5 6 7 8; 
    9 10 11 12 ] 

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [42]:
typeof(A)

Matrix{Int64} (alias for Array{Int64, 2})

In [43]:
v[0]

LoadError: BoundsError: attempt to access 4-element Vector{Int64} at index [0]

In [45]:
v[1]

1

In [46]:
A[1,1]

1

In [47]:
A[:, 2]

3-element Vector{Int64}:
  2
  6
 10

In [48]:
A[:, :]

3×4 Matrix{Int64}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [50]:
v1 = [1:10]

1-element Vector{UnitRange{Int64}}:
 1:10

In [51]:
v2 = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [52]:
typeof(v1)

Vector{UnitRange{Int64}} (alias for Array{UnitRange{Int64}, 1})

In [53]:
typeof(v2)

Vector{Int64} (alias for Array{Int64, 1})

In [54]:
v1[2:3]

LoadError: BoundsError: attempt to access 1-element Vector{UnitRange{Int64}} at index [2:3]

In [55]:
v2[2:3]

2-element Vector{Int64}:
 2
 3

In [57]:
# list comprehension도 가능함.
[x * 10 for x in 1:10]

10-element Vector{Int64}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

## 라이브러리 기반 자료형

In [59]:
using SparseArrays

In [60]:
SparseVector

SparseVector

In [61]:
SparseVector <: AbstractVector

true

In [62]:
Vector <: SparseVector

false

In [63]:
Vector <: AbstractVector

true

## Unicode

In [66]:
α = 10

10

In [67]:
β = 20

20

In [68]:
α + β

30

In [70]:
print("🍎")

🍎

In [71]:
🍎 = 10

10

In [72]:
🍌 = 20

20

In [73]:
🍉 = 40

40

In [74]:
fruits = [🍎, 🍌, 🍉]

print(fruits)

[10, 20, 40]

In [75]:
[fruit + 10 for fruit in fruits]

3-element Vector{Int64}:
 20
 30
 50

In [76]:
나 = 10
너 = 나 ^2 + 1

print(너)

101

In [ ]:


julia> 나 = 10 10

julia> 너 = 나^2 100

julia> for i in fruits println(i)

   end
ERROR: UndefVarError: fruits not defined Stacktrace: [1] top-level scope @ .\none:1

julia> for i in fruits println(i) end ERROR: UndefVarError: fruits not defined Stacktrace: [1] top-level scope @ .\none:1

julia> for i in fruits println(i) end ERROR: UndefVarError: fruits not defined Stacktrace: [1] top-level scope @ .\none:1

julia> for i in fruit println(i) end 10 20 40

julia> Γ = [1:2:10] 1-element Vector{StepRange{Int64, Int64}}: 1:2:9

julia> for γ in Γ println(γ) end 1:2:9

julia> for γ ∈ Γ println(γ) end 1:2:9

julia> function f(x) return x ^ 2 + 10 end f (generic function with 1 method)

julia> f(2) 14

julia> f(x) = x^2 + 10 f (generic function with 1 method)

julia> f(2) 14

julia> g(x, λ) = x^2 + λ^2 g (generic function with 1 method)

julia> g(2, 4) 20

julia> function h(x) x= 10 y = 20 x + y end h (generic function with 1 method)

julia> h(x) ERROR: UndefVarError: x not defined Stacktrace: [1] top-level scope @ none:1

julia> h h (generic function with 1 method)

julia> h(1) 30

julia> println("return은 기본적으로 맨 마지막 값을 따름") return은 기본적으로 맨 마지막 값을 따름

julia> funciton foo(x, y = 10; option = false) ERROR: syntax: extra token "foo" after end of expression

julia> function foo(x, y = 10; option = false) if option return x + y else return x^2 + y^2 end end foo (generic function with 2 methods)

julia> foo(1) 101

julia> foo(1, option = T) ERROR: UndefVarError: T not defined Stacktrace: [1] top-level scope @ none:1

julia> foo(1, option = true) 11

julia> foo(1, option = True) ERROR: UndefVarError: True not defined Stacktrace: [1] top-level scope @ none:1

julia> foo(1, 4; option = true) 5